[package]
name = "flat_head"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.21", features = ["derive"] }
decoder = { git = "https://github.com/semiotic-ai/flat-files-decoder.git", branch = "main" }
env_logger = "0.11.2"
# TODO: if the header accumulator changes to be public instead of internal set this to https
header_accumulator = { git = "ssh://git@github.com/semiotic-ai/header_accumulator.git", branch = "main" }
trin-validation = { git = "https://github.com/ethereum/trin.git", version = "0.1.0" }
tree_hash = "0.5.2"

log = "0.4.20"
