[package]
name = "flat_head"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.21", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
decoder = { git = "https://github.com/semiotic-ai/flat-files-decoder.git", branch = "main" }
env_logger = "0.11.2"
# TODO: if the header accumulator changes to be public instead of internal set this to https, and also change branch to main
header_accumulator = { git = "ssh://git@github.com/semiotic-ai/header_accumulator.git", branch = "refactor" }
trin-validation = { git = "https://github.com/ethereum/trin.git", version = "0.1.0" }
tree_hash = "0.5.2"
object_store = { version = "0.9.0", features = ["gcp", "http"] }
log = "0.4.20"
